FROM nginx:1.21-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./mime.types /etc/nginx/mime.types

RUN mkdir -p /etc/letsencrypt
COPY letsencrypt/ /etc/letsencrypt/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]